### ISSUE TITLE
NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

### ISSUE THREAD

**Issue by KNWBIN** [liyongjian5179/k8s-ansible#5]
--cni-conf-dir=/etc/cni/net.d \
--cni-bin-dir={{ workdir }}/cni/bin \
--root-dir={{ kubelet_storage_path }} \

在kubelet的配置中cni-bin-dir就是opt这个目录，calico默认就是这个目录，如果在修改了workdir这个变量为/data，这是kubelet中也就会变成--cni-bin-dir=/data/cni/bin,这样地址就不对了，所有就会报上面的错误，我找这个问题，找了好久啊，是别人帮我看到的，这个问题很关键啊

**Comment by liyongjian5179** [comment]
感谢提醒，在不改 calico 镜像的基础上是会有这个问题，可以先把这块的 {{ workdir }} 换成 `/opt`，我觉得为了更好的向后兼容还是不改 calico 那块比较好

**Comment by liyongjian5179** [comment]
刚看了一眼 flannel 那块的 role ，我是写死的，这块我稍后改一下推上去
